### PR TITLE
Working implementation of transparency mask

### PR DESCRIPTION
**Pull request by drhead**
This time it actually works.

This implements "add transparency mask" (which actually just merges the mask afterwards) as an option but is not quite at feature parity due to not auto hiding layers.

I have not tested it extensively.  It may not work when inpainting from a full image if there is no selection since I have not tested that.

### CODE REVIEW

**Comment by JasonS09** [comment]
Hey. Are you getting the transparency mask as output layers' children? In my case, the transparency mask is appearing as child of inpaint mask layer instead. I'm working with a batch of one image. Like this (whole image is selected). `setActiveNode(layer)` appears to keep being ignored:

**Comment by drhead** [comment]
I do get it correctly on mine (also it appears that auto hiding *was* working):
image

From testing with one image on certain settings, it seems that this can happen due to another race condition most likely.  I can't reproduce it in a debugger.  I'm going to look at fixing that and I think I found a better way to deal with race conditions and will test that.

**Comment by drhead** [comment]
I cannot figure out how to fix this issue in all cases.  Running in a debugger, setActiveNode(layer) is actually being ignored, but only when layer grouping is off and it is operating on a batch size of 1.  It works in all other cases.  It should at least work reliably with layer grouping now.  May just be best to use that as a workaround for now and move on, or to simply unpack the layer group at the end.

**Review by JasonS09 — APPROVED** [review]
Still getting the transparency mask as child of mask layer instead of output. However, I don't find this as a big deal (I mean it's just a matter of manually drag and drop). I'll leave it as a known issue. Good job!

**Comment by drhead** [comment]
If you do a pass over this in the future (which probably should happen as the old API is retired), I will say that applying a mask to the *group* would be a valid approach that is potentially easier and cleaner at the cost of making layer groups non-optional.

**Pull request merged**
